### ISSUE TITLE
token expired, how to fix?

### ISSUE THREAD

**Issue by github2alfred** [Azure-Samples/appinsights-guestbook#3]
>npm install
npm ERR! code E401
npm ERR! Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47, Basic realm="https://pkgsprodcus1.pkgs.visualstudio.com/", TFS-Federated

**Comment by markwolff** [comment]
Looks like an expired token was checked in. I deleted it so you can try it again
